import Foundation

/// Fatti brevi, uno per pausa.
///
/// **La regola che governa questo file, e che va letta prima di aggiungerci una riga.** Una fonte
/// precisa — autore, rivista, anno — si scrive **solo** quando è davvero quella. Dove il fatto è
/// consolidato ma la citazione puntuale non la conosco con certezza, l'attribuzione dice cos'è:
/// «fisiologia dell'esercizio, consenso scientifico», «linee guida OMS». **«Consenso» da solo non
/// basta:** in italiano è la parola dei moduli della privacy, e il 2026-07-31 il principale ha
/// dovuto chiedere cosa volesse dire. La forma è `<campo>, consenso scientifico`, sempre in
/// quest'ordine. Una citazione inventata bene è più
/// dannosa di nessuna citazione: è esattamente il difetto che l'app rimprovera ai concorrenti che
/// si dichiarano *science-backed* senza uno studio.
///
/// Gli studi **portanti** — quelli che giustificano i parametri della cadenza — non stanno qui:
/// stanno in `Evidence`, con link e tutto, e si aprono dal menu. Qui ci sono le briciole che
/// riempiono i secondi della pausa.
public enum Facts {

    /// **L'`id` resta ancorato all'italiano**, come per le citazioni: se seguisse la lingua
    /// mostrata, cambiare lingua darebbe a ogni fatto un'identità nuova e il mazzo ripartirebbe
    /// da zero senza che nessun errore lo dica.
    private static func f(_ text: String, _ source: String,
                          _ en: String = "", _ sourceEN: String = "") -> Phrase {
        Phrase(id: "f:\(text.prefix(28))", kind: .fatto, text: text, textEN: en,
               attribution: source, attributionEN: sourceEN.isEmpty ? source : sourceEN)
    }

    // MARK: - Stare seduti

    static let sedentarieta: [Phrase] = [
        f("Cinque minuti di movimento leggero ogni mezz'ora abbassano il picco glicemico dopo il pasto di quasi il 60%.",
          "Duran et al., Med Sci Sports Exerc, 2023",
          "Five minutes of light movement every half hour lower the post-meal glucose spike by almost 60%.",
          "Duran et al., Med Sci Sports Exerc, 2023"),
        f("Interrompere la seduta con tre minuti di squat ogni 45 minuti batte una camminata unica da mezz'ora, sul controllo glicemico.",
          "Gao et al., Scand J Med Sci Sports, 2024",
          "Breaking up sitting with three minutes of squats every 45 minutes beats a single half-hour walk for glycaemic control.",
          "Gao et al., Scand J Med Sci Sports, 2024"),
        f("Chi sta seduto oltre otto ore al giorno senza attività fisica ha un rischio di mortalità paragonabile a quello del fumo e dell'obesità.",
          "Ekelund et al., The Lancet, 2016",
          "Sitting more than eight hours a day without physical activity carries a mortality risk comparable to smoking and obesity.",
          "Ekelund et al., The Lancet, 2016"),
        f("Da sessanta a settantacinque minuti di attività moderata al giorno annullano il rischio in più di chi passa molte ore seduto.",
          "Ekelund et al., The Lancet, 2016",
          "Sixty to seventy-five minutes of moderate activity a day cancel the excess risk from many hours of sitting.",
          "Ekelund et al., The Lancet, 2016"),
        f("Chi si alza spesso ha girovita e trigliceridi migliori di chi resta fermo, a parità di ore passate sedute.",
          "Healy et al., Diabetes Care, 2008",
          "Breaking up sitting time often is associated with better waist circumference and triglycerides, at the same total hours seated.",
          "Healy et al., Diabetes Care, 2008"),
        // Gli asterischi del grassetto stavano nel testo e si vedevano a schermo come asterischi:
        // `Text` riceve la frase interpolata, e un valore interpolato non passa dal markdown.
        // Trovato guardando il provino il 2026-07-29; il cancello delle citazioni non poteva
        // vederlo, perché cerca il testo nella fonte e non sa com'è fatto lo schermo.
        f("Non conta quanto stai seduto in tutto: conta quanto a lungo resti seduto senza mai alzarti.",
          "ricerca sul comportamento sedentario, consenso scientifico",
          "It is not how long you sit in total, it is how long you sit without a break.",
          "consensus in sedentary behaviour research"),
        f("Restare seduti a lungo riduce l'attività della lipoproteina lipasi, l'enzima che ripulisce i grassi dal sangue.",
          "fisiologia dell'inattività, letteratura consolidata",
          "Sitting for long stretches reduces lipoprotein lipase activity, the enzyme that clears fat from the blood.",
          "physiology of inactivity, established literature"),
        f("Un muscolo inattivo smette di catturare glucosio anche quando l'insulina c'è: è la resistenza da immobilità.",
          "fisiologia dell'esercizio, consenso scientifico",
          "An inactive muscle stops taking up glucose even when insulin is present: that is immobility-driven resistance.",
          "exercise physiology consensus"),
        f("Le pause in piedi contano poco se resti fermo: è la contrazione muscolare a fare il lavoro, non la posizione.",
          "fisiologia dell'esercizio, consenso scientifico",
          "Standing breaks count for little if you stay still: it is muscle contraction that does the work, not the position.",
          "exercise physiology consensus"),
        f("La scrivania in piedi da sola non basta: cambia il carico, non l'immobilità.",
          "dichiarazione di consenso su sedentarietà e lavoro d'ufficio, Buckley et al., 2015",
          "A standing desk alone is not enough: it changes the load, not the stillness.",
          "consensus statement on sedentary behaviour and office work, Buckley et al., 2015"),
        f("Il sangue nelle gambe risale grazie alla pompa muscolare del polpaccio: senza contrazioni, ristagna.",
          "fisiologia cardiovascolare, nozione di base",
          "Blood returns from the legs thanks to the calf muscle pump: without contractions, it pools.",
          "cardiovascular physiology, basic knowledge"),
        f("Ore di immobilità aumentano il rischio di trombosi venosa: è lo stesso meccanismo della sindrome da classe economica.",
          "medicina vascolare, consenso scientifico",
          "Hours of immobility raise the risk of venous thrombosis: it is the same mechanism as economy class syndrome.",
          "vascular medicine consensus"),
        f("Anche due minuti di camminata ogni mezz'ora migliorano la risposta glicemica rispetto al restare seduti.",
          "letteratura sull'interruzione del tempo sedentario",
          "Even two minutes of walking every half hour improve the glucose response compared with staying seated.",
          "literature on breaking up sedentary time"),
        f("Il dispendio energetico di chi si muove spesso senza allenarsi può superare quello di chi si allena e poi sta fermo tutto il giorno.",
          "Levine, ricerca sulla termogenesi non da esercizio (NEAT)",
          "Someone who moves often without training can spend more energy than someone who trains and then sits all day.",
          "Levine, research on non-exercise activity thermogenesis (NEAT)"),
        f("I piccoli movimenti di tutti i giorni — alzarsi, camminare, non star fermo sulla sedia — spiegano differenze di centinaia di calorie al giorno fra persone simili.",
          "Levine, ricerca sulla termogenesi non da esercizio (NEAT)",
          "Small frequent movements — standing, walking, fidgeting — explain differences of hundreds of calories a day between similar people.",
          "Levine, research on non-exercise activity thermogenesis (NEAT)"),
    ]

    // MARK: - Muoversi poco e spesso

    static let movimento: [Phrase] = [
        f("Tre momenti al giorno di uno o due minuti di attività intensa, dentro la vita di tutti i giorni, si accompagnano a un rischio di morte più basso di circa il 40%.",
          "Stamatakis et al., Nature Medicine, 2022",
          "Three daily 1-2 minute bouts of vigorous activity in ordinary life are associated with about 40% lower mortality.",
          "Stamatakis et al., Nature Medicine, 2022"),
        f("Non serve allenarsi in senso stretto per avere benefici cardiovascolari: servono momenti duri, brevi e ripetuti.",
          "Stamatakis et al., Nature Medicine, 2022",
          "You do not need to train in the strict sense to get cardiovascular benefit: you need hard moments, short and repeated.",
          "Stamatakis et al., Nature Medicine, 2022"),
        f("Salire le scale è uno degli esercizi più intensi che si possano fare senza attrezzatura né spogliatoio.",
          "fisiologia dell'esercizio, consenso scientifico",
          "Climbing stairs is one of the most intense exercises you can do with no equipment and no changing room.",
          "exercise physiology consensus"),
        f("Il guadagno più grande si ha passando da zero movimento a poco, non da molto a moltissimo.",
          "curve dose-risposta dell'attività fisica, letteratura consolidata",
          "The largest benefit in terms of risk comes from going from no movement to a little — not from a lot to very much.",
          "dose-response curves for physical activity, established literature"),
        f("Le linee guida chiedono 150 minuti a settimana di attività moderata: sono poco più di venti minuti al giorno.",
          "linee guida OMS sull'attività fisica, 2020",
          "Guidelines ask for 150 minutes a week of moderate activity: that is a little over twenty minutes a day.",
          "WHO physical activity guidelines, 2020"),
        f("Le stesse linee guida raccomandano di rinforzare i muscoli almeno due volte a settimana. Quasi nessuno lo fa.",
          "linee guida OMS sull'attività fisica, 2020",
          "The same guidelines recommend strengthening your muscles at least twice a week. Almost nobody does.",
          "WHO physical activity guidelines, 2020"),
        f("Il muscolo scheletrico è il più grande organo di smaltimento del glucosio del corpo.",
          "fisiologia metabolica, nozione di base",
          "Skeletal muscle is the body's largest glucose disposal organ.",
          "metabolic physiology, basic knowledge"),
        f("Contrarre le gambe attiva trasportatori del glucosio anche senza insulina: è una via indipendente.",
          "fisiologia dell'esercizio, meccanismo GLUT4",
          "Contracting your legs activates glucose transporters even without insulin: it is an independent pathway.",
          "exercise physiology, the GLUT4 mechanism"),
        f("La forza delle gambe negli adulti predice l'autonomia in età avanzata meglio di molti esami del sangue.",
          "geriatria, letteratura su forza e funzione",
          "Leg strength in adults predicts independence in old age better than many blood tests.",
          "geriatrics, literature on strength and function"),
        f("La forza di presa della mano è uno dei predittori di mortalità più semplici e robusti che esistano.",
          "studi prospettici su forza di presa e mortalità",
          "Grip strength is one of the simplest and most robust predictors of mortality there is.",
          "prospective studies on grip strength and mortality"),
        f("La massa muscolare persa dopo i trent'anni si riprende a qualunque età con il sovraccarico: il muscolo risponde sempre.",
          "sarcopenia e allenamento di forza, consenso scientifico",
          "Muscle mass lost after thirty comes back at any age with overload: muscle always responds.",
          "consensus on sarcopenia and strength training"),
        f("L'osso si costruisce dove viene caricato: senza carico si disfa, con carico si ispessisce.",
          "legge di Wolff, ortopedia",
          "Bone builds where it is loaded: without load it breaks down, with load it thickens.",
          "Wolff's law, orthopaedics"),
        f("Il tendine si adatta più lentamente del muscolo: per questo la progressione graduale non è prudenza, è biologia.",
          "fisiologia del tessuto connettivo",
          "Tendon adapts more slowly than muscle: that is why gradual progression is not caution, it is biology.",
          "connective tissue physiology"),
        f("Un allenamento breve ripetuto più volte al giorno può produrre adattamenti simili a una sessione unica equivalente.",
          "letteratura sugli exercise snacks",
          "Short training repeated several times a day can produce adaptations similar to one equivalent single session.",
          "exercise snacks literature"),
        f("Bastano pochi minuti al giorno di esercizio intenso frazionato per migliorare la capacità cardiorespiratoria in poche settimane.",
          "letteratura sugli exercise snacks",
          "A few minutes a day of broken-up intense exercise are enough to improve cardiorespiratory capacity in a few weeks.",
          "exercise snacks literature"),
        f("La capacità aerobica è uno dei più forti predittori di longevità misurabili in laboratorio.",
          "epidemiologia della fitness cardiorespiratoria",
          "Aerobic capacity is one of the strongest predictors of longevity measurable in a laboratory.",
          "epidemiology of cardiorespiratory fitness"),
    ]

    // MARK: - Testa, occhi, attenzione

    static let mente: [Phrase] = [
        f("Il calo di attenzione dopo un'ora sullo stesso compito sparisce se lo si interrompe brevemente con un'attività diversa.",
          "Ariga & Lleras, Cognition, 2011",
          "The drop in attention after an hour on the same task disappears if you briefly interrupt it with a different activity.",
          "Ariga & Lleras, Cognition, 2011"),
        f("Le micro-pause sotto i dieci minuti stancano meno e fanno sentire più in forze, ma dopo un lavoro mentale pesante non bastano a far tornare la prestazione.",
          "Albulescu et al., PLOS ONE, 2022",
          "Micro-breaks under ten minutes reduce fatigue and raise vigour, but after intense cognitive work they are not enough to recover performance.",
          "Albulescu et al., PLOS ONE, 2022"),
        f("Le pause decise in anticipo battono quelle prese quando capita: stesso lavoro, stesso sforzo, meno tempo.",
          "Biwer et al., Br J Educ Psychol, 2023",
          "Breaks decided in advance beat breaks taken whenever: same work, same effort, less time.",
          "Biwer et al., Br J Educ Psychol, 2023"),
        f("Cinque minuti di pausa ogni ora riducono i disturbi muscoloscheletrici senza far calare la produttività misurata.",
          "Galinsky et al., Ergonomics, 2000",
          "Five minutes of break every hour reduce musculoskeletal discomfort with no measured drop in productivity.",
          "Galinsky et al., Ergonomics, 2000"),
        f("Davanti a uno schermo si sbatte le palpebre molto meno del normale: è la causa principale dell'occhio secco da computer.",
          "oftalmologia, letteratura su frequenza di ammiccamento e videoterminali",
          "In front of a screen you blink far less than normal: it is the main cause of computer-related dry eye.",
          "ophthalmology, literature on blink rate and display work"),
        f("Guardare lontano rilassa il muscolo ciliare, che tenendo il fuoco da vicino resta contratto per ore.",
          "ottica fisiologica, nozione di base",
          "Looking into the distance relaxes the ciliary muscle, which stays contracted for hours holding near focus.",
          "physiological optics, basic knowledge"),
        f("La regola 20-20-20 è ovunque, ma un confronto diretto fra intervalli diversi non ha trovato differenze su sintomi e lettura.",
          "Johnson & Rosenfield, letteratura optometrica, 2023",
          "The 20-20-20 rule is everywhere, but a direct comparison of different intervals found no difference in symptoms or reading.",
          "Johnson & Rosenfield, optometric literature, 2023"),
        f("Guardare qualcosa di naturale — anche solo dalla finestra — recupera l'attenzione meglio di guardare un altro schermo.",
          "teoria del ripristino dell'attenzione, Kaplan",
          "Looking at something natural — even just out of the window — restores attention better than looking at another screen.",
          "attention restoration theory, Kaplan"),
        f("La memoria di lavoro ha una capacità piccolissima: è il collo di bottiglia di quasi tutto quello che chiami «concentrazione».",
          "psicologia cognitiva, consenso scientifico",
          "Working memory has a tiny capacity: it is the bottleneck of almost everything you call \"concentration\".",
          "cognitive psychology consensus"),
        f("Cambiare compito costa un tempo di riorientamento che non si recupera: il multitasking è un cambio rapido, non un parallelismo.",
          "psicologia cognitiva, letteratura sul task switching",
          "Switching tasks costs a reorientation time you never get back: multitasking is fast switching, not parallelism.",
          "cognitive psychology, task switching literature"),
        f("Dopo un'interruzione, tornare al livello di concentrazione precedente richiede parecchi minuti.",
          "ricerca sulle interruzioni nel lavoro d'ufficio",
          "After an interruption, getting back to your previous level of concentration takes several minutes.",
          "research on interruptions in office work"),
        f("Il sonno consolida quello che hai imparato durante il giorno: studiare di più togliendo ore di sonno è un cattivo affare.",
          "neuroscienze del sonno, consenso scientifico",
          "Sleep consolidates what you learned during the day: studying more by cutting sleep is a bad trade.",
          "sleep neuroscience consensus"),
        f("La privazione di sonno peggiora i tempi di reazione in modo paragonabile a un tasso alcolico rilevante.",
          "medicina del sonno, studi su veglia prolungata e prestazione",
          "Sleep deprivation worsens reaction times to a degree comparable with a meaningful blood alcohol level.",
          "sleep medicine, studies on prolonged wakefulness and performance"),
        f("Un breve esercizio aerobico migliora l'umore in modo misurabile già dopo pochi minuti.",
          "psicologia dell'esercizio, meta-analisi su umore e attività acuta",
          "A short bout of aerobic exercise improves mood measurably within minutes.",
          "exercise psychology, meta-analyses on mood and acute activity"),
        f("Che novanta secondi di squat ti rendano più lucido subito dopo non è dimostrato: Otium interrompe per ragioni metaboliche, non per promesse cognitive.",
          "revisioni sull'esercizio acuto e funzioni esecutive, esito inconcludente",
          "That ninety seconds of squats make you sharper right afterwards is not established: Otium interrupts for metabolic reasons, not cognitive promises.",
          "reviews on acute exercise and executive function, inconclusive"),
        f("La sensazione di essere concentrati e l'esserlo davvero si scollano quando sei stanco: la prima resiste, la seconda no.",
          "psicologia della metacognizione, consenso scientifico",
          "The feeling of being focused and actually being focused come apart when you are tired: the first survives, the second does not.",
          "metacognition psychology consensus"),
    ]

    // MARK: - Schiena, collo, respiro

    static let posturaFatti: [Phrase] = [
        f("Non esiste una postura giusta: esiste il cambio di postura. Il carico statico è il problema, non l'angolo.",
          "ergonomia occupazionale, consenso scientifico",
          "There is no correct posture: there is changing posture. Static load is the problem, not the angle.",
          "occupational ergonomics consensus"),
        f("Il disco intervertebrale si nutre per diffusione, e la diffusione dipende dal movimento.",
          "biomeccanica del rachide, nozione di base",
          "The intervertebral disc feeds by diffusion, and diffusion depends on movement.",
          "spinal biomechanics, basic knowledge"),
        // Arrivata qui dal pool anonimo il 2026-07-29: è un fatto di fisiologia, non un pensiero,
        // e senza una fonte dichiarata stava nel posto sbagliato. La cartilagine non ha vasi e
        // vive del liquido sinoviale che il carico ciclico le fa entrare e uscire.
        f("Le articolazioni si nutrono di movimento, non di riposo.",
          "fisiologia articolare, nozione di base",
          "Joints feed on movement, not on rest.",
          "joint physiology, basic knowledge"),
        f("La pressione sui dischi lombari da seduti è maggiore che in piedi.",
          "biomeccanica del rachide, misurazioni classiche di Nachemson",
          "Pressure on the lumbar discs is higher seated than standing.",
          "spinal biomechanics, Nachemson's classic measurements"),
        f("Il dolore lombare cronico correla più con l'immobilità e la paura del movimento che con i reperti radiologici.",
          "medicina muscoloscheletrica, consenso scientifico",
          "Chronic low back pain correlates more with immobility and fear of movement than with radiological findings.",
          "musculoskeletal medicine consensus"),
        f("Molte alterazioni viste in risonanza — protrusioni, degenerazione — sono comuni anche in chi non ha alcun dolore.",
          "studi di imaging su popolazione asintomatica",
          "Many findings seen on MRI — bulges, degeneration — are common in people with no pain at all.",
          "imaging studies in asymptomatic populations"),
        f("Il collo in avanti moltiplica il carico sui muscoli cervicali: pochi centimetri pesano come chili.",
          "biomeccanica cervicale",
          "A forward head multiplies the load on the neck muscles: a few centimetres weigh like kilos.",
          "cervical biomechanics"),
        f("Respirare con il diaframma abbassa la frequenza cardiaca; respirare alto e corto la alza.",
          "fisiologia respiratoria, nozione di base",
          "Breathing with the diaphragm lowers heart rate; breathing high and short raises it.",
          "respiratory physiology, basic knowledge"),
        f("Un'espirazione più lunga dell'inspirazione attiva la risposta parasimpatica: è il modo più rapido di calmarsi.",
          "fisiologia autonomica, consenso scientifico",
          "An exhale longer than the inhale activates the parasympathetic response: it is the fastest way to calm down.",
          "autonomic physiology consensus"),
        f("Molte persone davanti allo schermo trattengono il respiro senza accorgersene, soprattutto mentre leggono email.",
          "osservazione documentata come «apnea da schermo», letteratura divulgativa",
          "Many people at a screen hold their breath without noticing, especially while reading email.",
          "documented as «screen apnoea», popular literature"),
        f("Il pavimento pelvico e il diaframma lavorano insieme: respirare male irrigidisce entrambi.",
          "fisioterapia, consenso scientifico",
          "The pelvic floor and the diaphragm work together: breathing badly stiffens both.",
          "physiotherapy consensus"),
    ]

    // MARK: - Abitudini

    static let abitudini: [Phrase] = [
        f("Un'abitudine nuova richiede in media un paio di mesi per diventare automatica, con enormi differenze fra persone.",
          "Lally et al., Eur J Soc Psychol, 2010",
          "A new habit takes on average a couple of months to become automatic, with huge differences between people.",
          "Lally et al., Eur J Soc Psychol, 2010"),
        f("Saltare un giorno singolo non compromette la formazione di un'abitudine.",
          "Lally et al., Eur J Soc Psychol, 2010",
          "Missing a single day does not compromise habit formation.",
          "Lally et al., Eur J Soc Psychol, 2010"),
        f("Legare un comportamento nuovo a un momento fisso della giornata funziona meglio della sola buona intenzione.",
          "letteratura sulle implementation intentions, Gollwitzer",
          "Tying a new behaviour to a fixed moment of the day works better than good intentions alone.",
          "implementation intentions literature, Gollwitzer"),
        f("Scrivere quando e dove farai una cosa aumenta molto la probabilità che la farai davvero.",
          "letteratura sulle implementation intentions, Gollwitzer",
          "Writing down when and where you will do something greatly raises the chance you actually will.",
          "implementation intentions literature, Gollwitzer"),
        f("Rendere un comportamento più facile da iniziare conta più che aumentare la motivazione.",
          "scienze comportamentali applicate, consenso scientifico",
          "Making a behaviour easier to start matters more than raising motivation.",
          "applied behavioural science consensus"),
        f("Gli avvisi che arrivano al momento giusto funzionano; quelli che arrivano sempre diventano rumore e si ignorano.",
          "ricerca sulle notifiche e l'affaticamento da allarme",
          "Alerts that arrive at the right moment work; alerts that always arrive become noise and get ignored.",
          "research on notifications and alarm fatigue"),
        f("Un obiettivo troppo grande produce meno azione di uno ridicolmente piccolo.",
          "scienze comportamentali applicate, consenso scientifico",
          "A goal that is too big produces less action than a ridiculously small one.",
          "applied behavioural science consensus"),
        f("Misurare un comportamento tende a cambiarlo, anche senza altri interventi.",
          "effetto della auto-osservazione, psicologia comportamentale",
          "Measuring a behaviour tends to change it, even with no other intervention.",
          "the self-monitoring effect, behavioural psychology"),
    ]

    // MARK: - Il corpo che nessuno guarda

    static let corpoSilenzioso: [Phrase] = [
        f("Il sistema linfatico non ha una pompa propria: si muove con la contrazione dei muscoli e il respiro.",
          "fisiologia, nozione di base",
          "The lymphatic system has no pump of its own: it moves with muscle contraction and breathing.",
          "physiology, basic knowledge"),
        f("Il cervello è circa il 2% del peso corporeo e consuma circa un quinto dell'energia a riposo.",
          "neurofisiologia, nozione di base",
          "The brain is about 2% of body weight and uses about a fifth of resting energy.",
          "neurophysiology, basic knowledge"),
        f("La disidratazione lieve basta a peggiorare umore e attenzione, ben prima che venga sete.",
          "letteratura su idratazione e prestazione cognitiva",
          "Mild dehydration is enough to worsen mood and attention, well before you feel thirsty.",
          "literature on hydration and cognitive performance"),
        f("La sete è un segnale tardivo: quando arriva, il calo è già cominciato.",
          "fisiologia dei fluidi, consenso scientifico",
          "Thirst is a late signal: by the time it arrives, the decline has already started.",
          "fluid physiology consensus"),
        f("Il picco di temperatura corporea nel pomeriggio coincide con il momento in cui la forza è massima.",
          "cronobiologia dell'esercizio, consenso scientifico",
          "The afternoon peak in body temperature coincides with the moment strength is highest.",
          "exercise chronobiology consensus"),
        f("La luce del mattino negli occhi è il segnale più forte per regolare l'orologio biologico.",
          "cronobiologia, consenso scientifico",
          "Morning light in your eyes is the strongest signal for setting your body clock.",
          "chronobiology consensus"),
        f("Guardare uno schermo luminoso a tarda sera ritarda l'inizio del sonno.",
          "medicina del sonno, letteratura sulla luce serale",
          "Looking at a bright screen late in the evening delays sleep onset.",
          "sleep medicine, literature on evening light"),
        f("Il caffè ha un'emivita di diverse ore: quello delle sedici è ancora in circolo a mezzanotte.",
          "farmacologia della caffeina, nozione di base",
          "Coffee has a half-life of several hours: the four o'clock one is still in you at midnight.",
          "caffeine pharmacology, basic knowledge"),
        f("L'attività fisica regolare è uno dei pochi interventi con effetto documentato su sonno, umore e metabolismo insieme.",
          "medicina preventiva, consenso scientifico",
          "Regular physical activity is one of the few interventions with a documented effect on sleep, mood and metabolism together.",
          "preventive medicine consensus"),
        f("Camminare dopo il pasto abbassa la glicemia postprandiale più che camminare a digiuno.",
          "letteratura su attività postprandiale e glicemia",
          "Walking after a meal lowers post-meal glucose more than walking on an empty stomach.",
          "literature on postprandial activity and glycaemia"),
        f("Anche due minuti di cammino dopo mangiato hanno un effetto misurabile sulla glicemia.",
          "meta-analisi su brevi camminate postprandiali",
          "Even two minutes of walking after eating have a measurable effect on blood glucose.",
          "meta-analyses on short postprandial walks"),
        f("Il freddo e il caldo si adattano; l'immobilità no: il corpo non impara mai a starci bene.",
          "fisiologia dell'adattamento, consenso scientifico",
          "You adapt to cold and heat; you never adapt to stillness: the body never learns to be fine with it.",
          "adaptation physiology consensus"),
        f("Il respiro è l'unica funzione autonoma che puoi guidare a piacere: è la porta di servizio del sistema nervoso.",
          "fisiologia autonomica, nozione di base",
          "Breathing is the only autonomic function you can drive at will: it is the service entrance to the nervous system.",
          "autonomic physiology, basic knowledge"),
        f("Alzarsi in piedi cambia immediatamente la distribuzione del sangue e la frequenza cardiaca.",
          "fisiologia cardiovascolare, nozione di base",
          "Standing up immediately changes blood distribution and heart rate.",
          "cardiovascular physiology, basic knowledge"),
        f("Il corpo umano è fatto per stare in piedi, camminare e accovacciarsi: la sedia ha meno di duecento anni di storia diffusa.",
          "antropologia della postura, consenso scientifico",
          "The human body is built to stand, walk and squat: the chair has less than two hundred years of widespread history.",
          "anthropology of posture, consensus"),
        f("Accovacciarsi profondamente è un movimento naturale che si perde con il disuso, non con l'età.",
          "letteratura su mobilità articolare e disuso",
          "A deep squat is a natural movement lost through disuse, not through age.",
          "literature on joint mobility and disuse"),
    ]

    /// Tutti i fatti brevi.
    public static let all: [Phrase] =
        sedentarieta + movimento + mente + posturaFatti + abitudini + corpoSilenzioso
}
